export const PROMISES_AREA = {
  signUp: 'sign-up',
  logIn: 'log-in',
  editProfile: 'edit-profile',
  changePassword: 'change-password',
  addAddresses: 'add-addresses',
  addOrder: 'add-order',
  cancelOrder: 'cancel-order',
  acceptOrder: 'accept-order',
  closeOrder: 'close-order',
  updateProduct: 'update-product',
  updateMenu: 'update-menu',
  removeProduct: 'remove-product',
  removeMenu: 'remove-menu',
  addIngredient: 'add-ingredient',
  removeIngredient: 'remove-ingredient',
};
